### ISSUE TITLE
Remove duplicate report_energy()

### ISSUE THREAD

**Issue by drewkunas** [nyu-cds/dk2755_assignment3#4]
In line 33-34, you have

```
    for _ in range(loops):
        report_energy(BODIES, bodies_pair)
        for _ in range(iterations):
```

And then in line 47 you have

`         print(report_energy(BODIES, bodies_pair))
`

The first report_energy() has no side effects, and doesn't print anything, so just remove it!

**Comment by dagshak** [comment]
Fixed it!
